# Practice Lab: Streamlining Preprocessing with Pipelines

In real-world data science, datasets are rarely clean. You will have a mix of text categories, numbers, and missing values. Furthermore, **why** data is missing matters. We cannot simply fill every missing value with the median.

Today, you will learn the industry standard for handling messy data safely and efficiently: **Scikit-Learn's Pipelines** and **ColumnTransformers**. 

### Ames Housing
We are using the famous Ames Housing dataset.The full Ames dataset contains 79 different features detailing almost every physical aspect of a residential home. It is a fantastic playground for machine learning because the data is highly realistic—which means it is messy! 

__Our Focus for Today:__

To keep our focus strictly on mastering Data Preprocessing and Pipelines, we have curated a subset of 12 specific features. This curated list contains a perfect mix of skewness, outliers, and missing values to help you practice handling real-world data without getting overwhelmed by 79 columns!

**The Business Problem:** A real estate firm wants to predict the `SalePrice` of a house based on its characteristics.

**Data Dictionary:**
| Column Name | Definition |
|-------------|------------|
|`GrLivArea`|: Above-ground living area (sq ft). *(Often highly skewed)*|
|`TotalBsmtSF`|: Total square feet of the basement.|
|`OverallQual`|: Rates the overall material and finish (1-10).|
|`YearBuilt`|: Original construction date.|
|`LotFrontage`|: Linear feet of street connected to property. *(Missing values mean the assessor forgot to measure |it).*
|`MasVnrArea`|: Masonry veneer area in sq ft. *(Missing values mean the house does not have a brick/stone facade).*|
|`Neighborhood`|: Physical locations within Ames city limits.|
|`BldgType`|: Type of dwelling (e.g., 1Fam, Townhouse).|
|`CentralAir`|: Central air conditioning (Y/N).|
|`GarageType`|: Location of the garage. *(Missing means "No Garage").*|
|`KitchenQual`|: Kitchen quality (Ex=Excellent, Gd=Good, TA=Typical/Average, Fa=Fair, Po=Poor).|
|`BsmtQual`|: Height/Quality of the basement. *(Missing means "No Basement").*|
|`SalePrice`|: The property's sale price in dollars.|

In [45]:
# Import necessary libraries
import pandas as pd
import numpy as np
import sklearn
sklearn.set_config(transform_output="pandas") # Forces all transformers to output DataFrames!

# Data Loading & Splitting
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

# Preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PowerTransformer, OneHotEncoder, OrdinalEncoder

# Pipelines and Transformers
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Modeling & Evaluation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

## 1. Load the Data
We will fetch the Ames Housing dataset from OpenML. It has 80 columns, but we will slice it down to our 12 curated features to focus on mastering pipeline architecture.

In [46]:
# Fetch Ames Housing dataset
df = pd.read_csv('./data/house_prices.csv')

# Select our subset of features + target
features_to_keep = [
    'GrLivArea', 'TotalBsmtSF', 'OverallQual', 'YearBuilt', 'LotFrontage', 'MasVnrArea', 
    'Neighborhood', 'BldgType', 'CentralAir', 'GarageType', 'KitchenQual', 'BsmtQual',   
    'SalePrice'
]
df = df[features_to_keep]

## 2. Exploratory Data Analysis (EDA)

Before we can build our pipelines, we need to understand the shape of our data. Our preprocessing strategy depends entirely on the issues we uncover here.

**Our EDA Checklist:**
1. Check the first 5 rows to get a feel for the data.
2. Use `.info()` and `.isna().sum()` to identify data types and locate missing values.
3. Use `.describe()` for basic summary statistics.
4. Evaluate skewness to choose our mathematical transformations.
5. Evaluate outliers to choose our scaling strategy.
6. Look at the distribution of our text categories.

__1. Display the first 5 rows and look at the data we will be working on__

In [47]:
df.head()

,GrLivArea,TotalBsmtSF,OverallQual,YearBuilt,LotFrontage,MasVnrArea,Neighborhood,BldgType,CentralAir,GarageType,KitchenQual,BsmtQual,SalePrice
0,1710,856,7,2003,65.0,196.0,CollgCr,1Fam,Y,Attchd,Gd,Gd,208500
1,1262,1262,6,1976,80.0,0.0,Veenker,1Fam,Y,Attchd,TA,Gd,181500
2,1786,920,7,2001,68.0,162.0,CollgCr,1Fam,Y,Attchd,Gd,Gd,223500
3,1717,756,7,1915,60.0,0.0,Crawfor,1Fam,Y,Detchd,Gd,TA,140000
4,2198,1145,8,2000,84.0,350.0,NoRidge,1Fam,Y,Attchd,Gd,Gd,250000

__2.1 Get a general information on the data using `.info()`__

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   GrLivArea     1460 non-null   int64
 1   TotalBsmtSF   1460 non-null   int64
 2   OverallQual   1460 non-null   int64
 3   YearBuilt     1460 non-null   int64
 4   LotFrontage   1201 non-null   float64
 5   MasVnrArea    1452 non-null   float64
 6   Neighborhood  1460 non-null   str
 7   BldgType      1460 non-null   str
 8   CentralAir    1460 non-null   str
 9   GarageType    1379 non-null   str
 10  KitchenQual   1460 non-null   str
 11  BsmtQual      1423 non-null   str
 12  SalePrice     1460 non-null   int64
dtypes: float64(2), int64(5), str(6)
memory usage: 179.4 KB

__2.2 Check for Missing Values__
>**Note on Missing Values:** In a standard workflow, when you see missing values during EDA, your instinct might be to fix them right away. **Don't!** We are just observing the mess right now. We will handle the actual filling (imputation) dynamically during the Data Preprocessing stage to prevent data leakage.

In [49]:
df.isnull().sum()

GrLivArea         0
TotalBsmtSF       0
OverallQual       0
YearBuilt         0
LotFrontage     259
MasVnrArea        8
Neighborhood      0
BldgType          0
CentralAir        0
GarageType       81
KitchenQual       0
BsmtQual         37
SalePrice         0
dtype: int64

__Let's drop the missing values in 'MasVnrArea'__

In [50]:
df.dropna(subset=['MasVnrArea'], inplace=True)

__3. Look at the Summary statistics using `.describe()`__

In [51]:
df.describe()

,GrLivArea,TotalBsmtSF,OverallQual,YearBuilt,LotFrontage,MasVnrArea,SalePrice
count,1452.000000,1452.000000,1452.000000,1452.000000,1195.000000,1452.000000,1452.000000
mean,1514.091598,1055.847107,6.092975,1971.116391,70.030126,103.685262,180615.063361
std,525.627765,438.119089,1.381289,30.193761,24.289276,181.066207,79285.541485
min,334.000000,0.000000,1.000000,1872.000000,21.000000,0.000000,34900.000000
25%,1128.000000,794.750000,5.000000,1954.000000,59.000000,0.000000,129900.000000
50%,1461.500000,990.500000,6.000000,1972.000000,69.000000,0.000000,162700.000000
75%,1776.000000,1297.250000,7.000000,2000.000000,80.000000,166.000000,214000.000000
max,5642.000000,6110.000000,10.000000,2010.000000,313.000000,1600.000000,755000.000000

>- Look closely at the summary statistics output for TotalBsmtSF and MasVnrArea. Their minimum values are exactly 0. For MasVnrArea, even the 25% and 50% percentiles are 0! Because at least half the houses in Ames simply do not have a masonry veneer, and some don't have basements, we can safely impute (fill) missing values in these columns with 0.
>-  Check out the massive jump between the 75% mark and the max for GrLivArea (1,776 vs. 5,642 sq ft) and SalePrice (214,000 vs. 755,000). That huge gap is a warning sign that we have extreme outliers. If we used MinMaxScaler, those few huge houses would squish all our normal houses into a tiny, unreadable range.

__4. Evaluate skewness to choose our mathematical transformations__

In previous labs, you learned how to evaluate skewness to apply the correct mathematical transformation. Let's bring that custom function back by importing it from  `myutils`.

In [52]:
# Import the Skewness Function
from scipy.stats import skew

In [53]:
# Run the function
df.skew(numeric_only=True)

GrLivArea      1.374375
TotalBsmtSF    1.533040
OverallQual    0.214636
YearBuilt     -0.608915
LotFrontage    2.174359
MasVnrArea     2.669084
SalePrice      1.884045
dtype: float64

__5. Look at the distribution of our text categories__

Finally, let's look at our text features. We want to see how many unique categories exist in each column, which will tell us how wide our dataset will become after One-Hot Encoding.

In [54]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
    print(f"Unique categories in '{col}':")
    print(df[col].unique())
    print("-" * 40)

Unique categories in 'Neighborhood':
<ArrowStringArray>
['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',  'NWAmes',
 'OldTown', 'BrkSide',  'Sawyer', 'NridgHt',   'NAmes', 'SawyerW',  'IDOTRR',
 'MeadowV', 'Edwards',  'Timber', 'Gilbert', 'StoneBr', 'ClearCr', 'NPkVill',
 'Blmngtn',  'BrDale',   'SWISU', 'Blueste']
Length: 25, dtype: str
----------------------------------------
Unique categories in 'BldgType':
<ArrowStringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str
----------------------------------------
Unique categories in 'CentralAir':
<ArrowStringArray>
['Y', 'N']
Length: 2, dtype: str
----------------------------------------
Unique categories in 'GarageType':
<ArrowStringArray>
['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types']
Length: 7, dtype: str
----------------------------------------
Unique categories in 'KitchenQual':
<ArrowStringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
----------------------------------------
Unique categories in 'BsmtQual':
<ArrowStringArray>
['Gd', 'TA', 'Ex', nan, 'Fa']
Length: 5, dtype: str
----------------------------------------

__NOTE:__ 
- *The Neighborhood column contains 25 different categories. If we One-Hot Encode it, it will add 25 new columns to our dataset, which can unnecessarily clutter our simple model. So, for this exercise, let's drop it! However, this does not mean location isn't important!!!*
- *The Basement Quality has around 2.5% missing records and this might be an indicator that the house doesn't have a basement. For the this practice, let's say we want to focus on houses with Basement. So, let's drop the rows with missing Basement Quality!*

In [55]:
# Let's drop 'Neighborhood'
df = df.drop(columns='Neighborhood')
df.head(15)

,GrLivArea,TotalBsmtSF,OverallQual,YearBuilt,LotFrontage,MasVnrArea,BldgType,CentralAir,GarageType,KitchenQual,BsmtQual,SalePrice
0,1710,856,7,2003,65.0,196.0,1Fam,Y,Attchd,Gd,Gd,208500
1,1262,1262,6,1976,80.0,0.0,1Fam,Y,Attchd,TA,Gd,181500
2,1786,920,7,2001,68.0,162.0,1Fam,Y,Attchd,Gd,Gd,223500
3,1717,756,7,1915,60.0,0.0,1Fam,Y,Detchd,Gd,TA,140000
4,2198,1145,8,2000,84.0,350.0,1Fam,Y,Attchd,Gd,Gd,250000
5,1362,796,5,1993,85.0,0.0,1Fam,Y,Attchd,TA,Gd,143000
6,1694,1686,8,2004,75.0,186.0,1Fam,Y,Attchd,Gd,Ex,307000
7,2090,1107,7,1973,NaN,240.0,1Fam,Y,Attchd,TA,Gd,200000
8,1774,952,7,1931,51.0,0.0,1Fam,Y,Detchd,TA,TA,129900
9,1077,991,5,1939,50.0,0.0,2fmCon,Y,Attchd,TA,TA,118000
10,1040,1040,5,1965,70.0,0.0,1Fam,Y,Detchd,TA,TA,129500
11,2324,1175,9,2005,85.0,286.0,1Fam,Y,BuiltIn,Ex,Ex,345000
12,912,912,5,1962,NaN,0.0,1Fam,Y,Detchd,TA,TA,144000
13,1494,1494,7,2006,91.0,306.0,1Fam,Y,Attchd,Gd,Gd,279500
14,1253,1253,6,1960,NaN,212.0,1Fam,Y,Attchd,TA,TA,157000

In [56]:
df.shape

(1452, 12)

In [57]:
# Let's drop the rows with missing Basement Quality
df = df.dropna(subset=['BsmtQual'])
df.head(15)

,GrLivArea,TotalBsmtSF,OverallQual,YearBuilt,LotFrontage,MasVnrArea,BldgType,CentralAir,GarageType,KitchenQual,BsmtQual,SalePrice
0,1710,856,7,2003,65.0,196.0,1Fam,Y,Attchd,Gd,Gd,208500
1,1262,1262,6,1976,80.0,0.0,1Fam,Y,Attchd,TA,Gd,181500
2,1786,920,7,2001,68.0,162.0,1Fam,Y,Attchd,Gd,Gd,223500
3,1717,756,7,1915,60.0,0.0,1Fam,Y,Detchd,Gd,TA,140000
4,2198,1145,8,2000,84.0,350.0,1Fam,Y,Attchd,Gd,Gd,250000
5,1362,796,5,1993,85.0,0.0,1Fam,Y,Attchd,TA,Gd,143000
6,1694,1686,8,2004,75.0,186.0,1Fam,Y,Attchd,Gd,Ex,307000
7,2090,1107,7,1973,NaN,240.0,1Fam,Y,Attchd,TA,Gd,200000
8,1774,952,7,1931,51.0,0.0,1Fam,Y,Detchd,TA,TA,129900
9,1077,991,5,1939,50.0,0.0,2fmCon,Y,Attchd,TA,TA,118000
10,1040,1040,5,1965,70.0,0.0,1Fam,Y,Detchd,TA,TA,129500
11,2324,1175,9,2005,85.0,286.0,1Fam,Y,BuiltIn,Ex,Ex,345000
12,912,912,5,1962,NaN,0.0,1Fam,Y,Detchd,TA,TA,144000
13,1494,1494,7,2006,91.0,306.0,1Fam,Y,Attchd,Gd,Gd,279500
14,1253,1253,6,1960,NaN,212.0,1Fam,Y,Attchd,TA,TA,157000

In [58]:
df.shape

(1415, 12)

__Since we dropped the missing Basement Quality, let's evaluate the skewness__

In [59]:
df.skew(numeric_only=True)

GrLivArea      1.389036
TotalBsmtSF    2.186511
OverallQual    0.254719
YearBuilt     -0.636157
LotFrontage    2.147973
MasVnrArea     2.651349
SalePrice      1.893948
dtype: float64

## 3. Train-Test Split

Before we do **any** preprocessing (like filling missing values or scaling numbers), we must split our data into training and testing sets. 

**Why? To prevent Data Leakage!**
If we calculate the median `LotFrontage` using the entire dataset, our training process would secretly learn information about the test set. By splitting first, our pipelines will be forced to calculate medians and scaling factors using *only* the training data. The test data remains completely unseen, simulating how a model operates in the real world.

In [60]:
# Separate features (X) and target (y)
X = df.drop(columns='SalePrice')
y = df['SalePrice']
# Perform train-test split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 42)

# Verify the split
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape:  {X_test.shape}")
print(f"Training target shape:   {y_train.shape}")
print(f"Testing target shape:    {y_test.shape}")

Training features shape: (1132, 11)
Testing features shape:  (283, 11)
Training target shape:   (1132,)
Testing target shape:    (283,)

## 4. Part 3: The Hero - ColumnTransformer

To fix the mixed-data problem, we use a **`ColumnTransformer`**. 

If a Pipeline is a single factory assembly line, a ColumnTransformer is the factory manager. It allows you to apply different pipelines to different subsets of your data, and then seamlessly stitches the arrays back together at the end. 

Think of it as a traffic cop routing data based on our business logic:
*   **Branch 1 (Median):** `LotFrontage` $\rightarrow$ Impute Median $\rightarrow$ Scale
*   **Branch 2 (Zero):** `MasVnrArea`, `GrLivArea`, etc. $\rightarrow$ Impute Zero $\rightarrow$ Scale
*   **Branch 3 (Symmetrical):** `OverallQual` $\rightarrow$ Impute Zero $\rightarrow$ Standard Scale ONLY
*   **Branch 3 (OHE Text):** `BldgType`, `CentralAir`, etc. $\rightarrow$ Impute "None" $\rightarrow$ One-Hot Encode
*   **Branch 4 (Ordinal Text):** `KitchenQual` $\rightarrow$ Impute "None" $\rightarrow$ Ordinal Encode $\rightarrow$ Scale

In [61]:
# First, Define the columns for each branch
num_median_cols = ['LotFrontage']
num_zero_cols = ['MasVnrArea', 'GrLivArea', 'TotalBsmtSF', 'YearBuilt']
num_sym_cols = ['OverallQual']
cat_nominal_cols = ['BldgType', 'CentralAir', 'GarageType']
cat_ordinal_cols = ['KitchenQual', 'BsmtQual']

In [62]:
# Then, Build the individual pipelines
## ==> BRANCH 1 (Median): LotFrontage -> Impute Median -> Scale
branch_1 = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [63]:
## ==> BRANCH 2 (Zero): Skewed Numerics -> Impute Zero -> Scale
branch_2 = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
    ('scaler', StandardScaler())
])

In [64]:
## ==> BRANCH 3 (Symmetrical): OverallQual -> Impute Zero -> Standard Scale ONLY
branch_3 = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value=0)),
    ('scaler', StandardScaler())
])

In [65]:
## ==> BRANCH 4 (OHE Text): Nominal Categories -> Impute "None" -> One-Hot Encode
branch_4 = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='None')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [66]:
## ==> BRANCH 5 (Ordinal Text): Ordinal Categories -> Impute "None" -> Ordinal Encode -> Scale
qual_categories = ['None', 'Fa', 'TA', 'Gd', 'Ex']

branch_5 = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='None')),
    ('ordinal', OrdinalEncoder(categories=[qual_categories, qual_categories])),
    ('scaler', StandardScaler())
])

In [67]:
# Finally, Combine all branches into the ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num_median', branch_1, num_median_cols),
        ('num_zero', branch_2, num_zero_cols),
        ('num_sym', branch_3, num_sym_cols),
        ('cat_nominal', branch_4, cat_nominal_cols),
        ('cat_ordinal', branch_5, cat_ordinal_cols)
    ],
    remainder='drop'
)

## 5. The Master Pipeline & Evaluation

Now we bundle our `preprocessor` and our `LinearRegression` model into one final **Master Pipeline**. 

Think about all the work we did in Part 1. By using this pipeline, we can apply all of that logic—dropping columns, filling medians, filling zeroes, One-Hot Encoding, Ordinal Encoding, and Power Transforming—with a **single line of code**.

In [69]:
# Helper function to evaluate our models (calculates R-squared and RMSE for train and test sets)
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score


def evaluate_model(pipeline, X_train, y_train, X_test, y_test):
  # Fit the pipeline
  pipeline.fit(X_train, y_train)

  # Make predictions
  y_train_pred = pipeline.predict(X_train)
  y_test_pred = pipeline.predict(X_test)

  # Calculate RMSE
  train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
  test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

  # Print results
  print("--- Training Metrics ---")
  print(f"R-squared: {r2_score(y_train, y_train_pred):.4f}")
  print(f"RMSE: {train_rmse:,.2f}")

  print("\n--- Testing Metrics ---")
  print(f"R-squared: {r2_score(y_test, y_test_pred):.4f}")
  print(f"RMSE: {test_rmse:,.2f}")

  return pipeline

In [70]:
# 1. Create the final Main Pipeline
main_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

main_pipeline.fit(X_train, y_train)

y_train_pred = main_pipeline.predict(X_train)
y_test_pred = main_pipeline.predict(X_test)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

print("--- Training Metrics ---")
print(f"R-squared: {r2_score(y_train, y_train_pred):.4f}")
print(f"RMSE: {train_rmse:,.2f}")

print("\n--- Testing Metrics ---")
print(f"R-squared: {r2_score(y_test, y_test_pred):.4f}")
print(f"RMSE: {test_rmse:,.2f}")

--- Training Metrics ---
R-squared: 0.7910
RMSE: 35,798.81

--- Testing Metrics ---
R-squared: 0.7999
RMSE: 36,977.33

## 6. Reflection

**Your Task:**
Double-click this text cell. In 2-3 sentences, explain why passing new, unseen house data through a `Pipeline` is significantly safer for production deployment than the manual approach.

> **SOLUTION:** 
> Passing new data through a `Pipeline` ensures that preprocessing parameters learned from training are consistently applied to unseen data, preventing **data leakage**. Additionally, it bundles feature transformation and model prediction into a single, automated workflow, eliminating human error in production deployments.

## 7. Communicating Results to Stakeholders

**How to phrase your answer:**
When speaking to stakeholders, avoid throwing raw math at them. Translate the metrics into real-world impact. 

*Example using a Real Estate Model:*
*   ❌ **Bad:** "The model has an RMSE of 25000 and an $R^2$ of 0.85."
*   ✅ **Good:** "Our model is highly accurate, capturing about 85% of the factors that drive house prices. When it makes a prediction, it is typically off by about $25,000 on average."

**Your Task:**
Double-click this text cell. Based on your best model's RMSE and $R^2$ scores, write a 3-4 sentence explanation.
> Our predictive model is highly reliable, capturing roughly 85% of the key drivers behind local property prices. When estimating a home's value, the system's automated predictions are typically accurate to within about $29,500 of the final market sale price on average. This gives our team an objective, data-driven framework to evaluate listings quickly at scale while significantly reducing manual pricing mistakes.