<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Exercise - `pandas` Long Format, Wide Format, Pivot Tables, and Melting
---

## Exercise:

#### 1. Convert the NPAS_parsed_trunc_long.csv dataset from long to wide

In [78]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [103]:
# load the data
nerdy_long = pd.read_csv('./data/NPAS_parsed_trunc_long.csv')

In [104]:
nerdy_long.head()

   subject_id   variable value
0           1  education   4.0
1           2  education   3.0
2           5  education   2.0
3           6  education   2.0
4           7  education   2.0

In [105]:
# check shape
nerdy_long.shape

(70295, 3)

You can see that the long format data has far more rows than the wide data set but only three columns.

Below you can view the three columns: `subject_id`, `variable`, and `value`.

**`subject_id:`**
- This is the primary "key" or `ID` column. Each `subject_id` will have corresponding entries in the `variable` column — one for each row.

**`variable:`**
- This column indicates the variable with which the item in the `value` column corresponds.

**`value:`**

- This contains all values for all variables for all IDs. Essentially, every cell in the wide data set except the `subject_id` is listed in this column.

In [109]:
# filter subject_id ==1
nerdy_long[nerdy_long['subject_id'] == 1]
nerdy_long

       subject_id          variable value
0               1         education   4.0
1               2         education   3.0
2               5         education   2.0
3               6         education   2.0
4               7         education   2.0
...           ...               ...   ...
70290        1386  socially_awkward   4.0
70291        1387  socially_awkward   5.0
70292        1388  socially_awkward   3.0
70293        1389  socially_awkward   4.0
70294        1390  socially_awkward   5.0

[70295 rows x 3 columns]

**Print out the unique values in the `variable` column.**

You can see that the unique values in the `variable` column correspond to the column headers in the wide format data.

In [110]:
# show unique values in the variable column
nerdy_long['variable'].unique()

<ArrowStringArray>
[                   'education',                        'urban',
                       'gender',                       'engnat',
                          'age',                         'hand',
                     'religion',                        'voted',
                      'married',                   'familysize',
                        'major',                   'race_white',
                   'race_nerdy',         'race_native_american',
                'writing_novel',            'read_tech_reports',
         'online_over_inperson',                'introspective',
          'hobbies_over_people',           'books_over_parties',
                      'bookish',   'libraries_over_publicspace',
      'race_native_austrailian',           'like_hard_material',
                'race_hispanic',           'diagnosed_autistic',
         'play_many_videogames',                    'race_arab',
                   'race_asian',           'interested_science',
                  'playes_rpgs',          'in_advanced_classes',
                'collect_books', 'intelligence_over_appearance',
          'watch_science_shows',         'academic_over_social',
         'like_science_fiction',              'like_dry_topics',
                   'race_black',                         'calm',
                 'disorganized',                  'extraverted',
                   'dependable',                     'critical',
                    'opennness',                      'anxious',
                  'sympathetic',                     'reserved',
                 'conventional',                'was_odd_child',
      'prefer_fictional_people',               'enjoy_learning',
       'excited_about_research',               'strange_person',
             'like_superheroes',             'socially_awkward']
Length: 56, dtype: str

 **Convert from long to wide**

In [113]:
# convert from long to wide
nerdy_wide = nerdy_long.pivot(index='subject_id', 
                              columns='variable', 
                              values='value').reset_index()

# check the head
nerdy_wide.head()

variable,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [114]:
# check the shape of the new created wide dataframe
nerdy_wide.shape

(1391, 57)

In [115]:
# Remove the column label
nerdy_wide.columns.name = None

# check the head again
nerdy_wide.head()

,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [116]:
# save wide data to csv as nerdy_wide.csv
nerdy_wide.to_csv('nerdy_wide.csv')

#### 2. Convert it back from wide to long
- Keep `subject_id` and `major` as the `Columns that stay locked`

In [117]:
# check the head of nerdy_wide
nerdy_wide.head()

,subject_id,academic_over_social,age,anxious,bookish,books_over_parties,calm,collect_books,conventional,critical,...,religion,reserved,socially_awkward,strange_person,sympathetic,urban,voted,was_odd_child,watch_science_shows,writing_novel
0,0,5.0,NaN,1.0,5.0,5.0,7.0,5.0,1.0,1.0,...,NaN,7.0,5.0,5.0,7.0,NaN,NaN,5.0,5.0,3.0
1,1,2.0,50.0,4.0,4.0,4.0,6.0,5.0,1.0,3.0,...,1.0,5.0,5.0,4.0,5.0,2.0,1.0,3.0,5.0,1.0
2,2,5.0,22.0,7.0,5.0,5.0,2.0,5.0,1.0,6.0,...,1.0,7.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,4.0
3,3,5.0,NaN,4.0,4.0,5.0,7.0,5.0,1.0,2.0,...,NaN,2.0,5.0,5.0,6.0,NaN,NaN,5.0,5.0,4.0
4,4,4.0,NaN,3.0,5.0,5.0,6.0,4.0,2.0,5.0,...,NaN,6.0,0.0,5.0,5.0,NaN,NaN,5.0,4.0,1.0

In [119]:
nerdy_wide.columns.tolist()[:]

['subject_id',
 'academic_over_social',
 'age',
 'anxious',
 'bookish',
 'books_over_parties',
 'calm',
 'collect_books',
 'conventional',
 'critical',
 'dependable',
 'diagnosed_autistic',
 'disorganized',
 'education',
 'engnat',
 'enjoy_learning',
 'excited_about_research',
 'extraverted',
 'familysize',
 'gender',
 'hand',
 'hobbies_over_people',
 'in_advanced_classes',
 'intelligence_over_appearance',
 'interested_science',
 'introspective',
 'libraries_over_publicspace',
 'like_dry_topics',
 'like_hard_material',
 'like_science_fiction',
 'like_superheroes',
 'major',
 'married',
 'online_over_inperson',
 'opennness',
 'play_many_videogames',
 'playes_rpgs',
 'prefer_fictional_people',
 'race_arab',
 'race_asian',
 'race_black',
 'race_hispanic',
 'race_native_american',
 'race_native_austrailian',
 'race_nerdy',
 'race_white',
 'read_tech_reports',
 'religion',
 'reserved',
 'socially_awkward',
 'strange_person',
 'sympathetic',
 'urban',
 'voted',
 'was_odd_child',
 'watch_science_shows',
 'writing_novel']

In [122]:
# do the convert
nerdy_long_again = pd.melt(frame=nerdy_wide,
                            id_vars=['subject_id', 'major'],
                                    var_name='variable',
                                    value_name='value')

# check the head
nerdy_long_again

       subject_id                   major              variable value
0               0                     NaN  academic_over_social   5.0
1               1              biophysics  academic_over_social   2.0
2               2                 biology  academic_over_social   5.0
3               3                     NaN  academic_over_social   5.0
4               4                     NaN  academic_over_social   4.0
...           ...                     ...                   ...   ...
76500        1386  biomedical engineering         writing_novel   5.0
76501        1387                     NaN         writing_novel   2.0
76502        1388                 unknown         writing_novel   3.0
76503        1389        Computer Science         writing_novel   1.0
76504        1390                 Science         writing_novel   1.0

[76505 rows x 4 columns]

In [123]:
# get the shape of the dataset
nerdy_long_again.shape

(76505, 4)

#### 3. Convert again from wide to long but with a selected value_vars
- Create the same DataFrame with `.melt()` on the full wide data set, but select the columns 'anxious','bookish','calm' to be used with the `value_vars` argument
- name the new dataframe with a different name than the previous

In [125]:
# do the convert, call the dataframe with some other name
nerdy_long_selected = pd.melt(frame=nerdy_wide,
                            id_vars=['subject_id', 'major'],
                            value_vars=['anxious', 'bookish', 'calm'])
    
# check the head
nerdy_long_selected.head()

   subject_id       major variable value
0           0         NaN  anxious   1.0
1           1  biophysics  anxious   4.0
2           2     biology  anxious   7.0
3           3         NaN  anxious   4.0
4           4         NaN  anxious   3.0

In [126]:
# get the shape of the dataset
nerdy_long_selected.shape

(4173, 4)