# 01: Data Collection
### Stack Overflow Developer Survey: Exploratory Data Analysis

**Name:** Sara AlNajjar  
**Project:** Project 2: Exploratory Data Analysis   
General Assembly DSBFT2   

---
## Problem

> A coding bootcamp wants to know which programming languages and tools are associated with the highest compensation and the strongest year-over-year growth, so it can prioritize curriculum around the tech stacks that yield the best outcomes for graduates.

## Approach

**Approach 1: Curriculum Optimization for High-Yield Tech Stacks.**   
This notebook loads the 2024 and 2025 Stack Overflow Developer Survey datasets, filters to US respondents, reconciles schema differences between the two survey years, cleans and combines the data, then explores compensation by programming language to identify which languages are worth prioritizing in curriculum design.

---

## 1. Installs

In [12]:
# !pip install pandas numpy matplotlib

In [13]:
# initial imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

---

## 2. Data Loading

In [35]:
# Load 2024 and 2025 survey data separately
df24 = pd.read_csv('./Data/Survey 2024/survey_results_2024.csv', low_memory=False)
df25 = pd.read_csv('./Data/Survey 2025/survey_results_2025.csv', low_memory=False)

In [36]:
df24.shape, df25.shape

((65437, 114), (49191, 172))

In [22]:
df24.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [38]:
df24.info()

<class 'pandas.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), str(100)
memory usage: 195.7 MB

In [34]:
df25.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [25]:
df25.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 176.2 MB

---

## 3. Comparing Schemas Across Years

In [75]:
cols_in_24 = set(df24.columns) - set(df25.columns)
cols_in_25 = set(df25.columns) - set(df24.columns)

print('Columns only in 2024:', cols_in_24)
print('Columns only in 2025:', cols_in_25)

Columns only in 2024: {'Frequency_3', 'NEWCollabToolsWantToWorkWith', 'SOHow', 'SurveyEase', 'AINextNo change', 'TechDoc', 'AINextMuch less integrated', 'AINextMore integrated', 'NEWCollabToolsAdmired', 'MiscTechHaveWorkedWith', 'YearsCodePro', 'OfficeStackSyncAdmired', 'NEWCollabToolsHaveWorkedWith', 'ProfessionalTech', 'TechEndorse', 'Knowledge_6', 'Frequency_2', 'TimeSearching', 'TimeAnswering', 'ToolsTechHaveWorkedWith', 'Knowledge_1', 'AISearchDevWantToWorkWith', 'CodingActivities', 'Check', 'BuyNewTool', 'Knowledge_2', 'Knowledge_8', 'AIChallenges', 'EmbeddedAdmired', 'AISearchDevHaveWorkedWith', 'Knowledge_9', 'Frustration', 'AIToolInterested in Using', 'ToolsTechWantToWorkWith', 'EmbeddedHaveWorkedWith', 'AIBen', 'Knowledge_7', 'LearnCodeOnline', 'Frequency_1', 'ProfessionalQuestion', 'OfficeStackSyncWantToWorkWith', 'MiscTechAdmired', 'AINextMuch more integrated', 'EmbeddedWantToWorkWith', 'ToolsTechAdmired', 'AINextLess integrated', 'ProfessionalCloud', 'Knowledge_4', 'NEWSOSites', 'OfficeStackSyncHaveWorkedWith', 'AIToolCurrently Using', 'AISearchDevAdmired', 'AIEthics', 'Knowledge_5', 'MiscTechWantToWorkWith', 'SurveyLength', 'Knowledge_3', 'BuildvsBuy', 'TBranch', 'AIToolNot interested in Using'}
Columns only in 2025: {'AIExplain', 'AIModelsWantToWorkWith', 'TechOppose_16', 'TechEndorse_9', 'TechOppose_7', 'SO_Actions_9', 'AIAgentChallengesStrongly disagree', 'DevEnvHaveEntry', 'WebframeWantEntry', 'AIToolCurrently mostly AI', 'SOTagsWant Entry', 'WebframeHaveEntry', 'TechEndorseIntro', 'SOTagsAdmired', 'JobSatPoints_16', 'DatabaseChoice', 'TechOppose_5', 'CommPlatformAdmired', 'TechOppose_15_TEXT', 'AIAgentImpactSomewhat agree', 'TechEndorse_5', 'LanguageChoice', 'NewRole', 'LearnCodeChoose', 'DevEnvWantEntry', 'DatabaseWantEntry', 'LanguagesWantEntry', 'TechOppose_9', 'DatabaseHaveEntry', 'PlatformChoice', 'JobSatPoints_15_TEXT', 'OfficeStackHaveEntry', 'TechOppose_1', 'SO_Actions_3', 'SO_Actions_10', 'ToolCountWork', 'CommPlatformWantEntr', 'AIToolPlan to mostly use AI', 'TechOppose_15', 'TechEndorse_13_TEXT', 'JobSatPoints_3', 'DevEnvsHaveWorkedWith', 'SOTagsHaveWorkedWith', 'TechEndorse_2', 'CommPlatformHaveWorkedWith', 'JobSatPoints_14', 'DevEnvsWantToWorkWith', 'AIModelsAdmired', 'AIAgentKnowWrite', 'AgentUsesGeneral', 'SO_Actions_6', 'AIAgentOrchestration', 'AILearnHow', 'AIModelsChoice', 'ToolCountPersonal', 'TechOppose_3', 'AIToolPlan to partially use AI', 'SO_Actions_16', 'SO_Actions_7', 'SOTagsHaveEntry', 'AIAgentChallengesNeutral', 'AIOpen', 'AIAgent_Uses', 'JobSatPoints_15', 'TechOppose_13', 'OfficeStackWantEntry', 'PlatformWantEntry', 'AIModelsHaveEntry', 'AIAgentImpactNeutral', 'SOTagsWantToWorkWith', 'LanguagesHaveEntry', 'EmploymentAddl', 'DevEnvsAdmired', 'SO_Actions_5', 'SO_Actions_1', 'TechEndorse_7', 'AIModelsHaveWorkedWith', 'TechEndorse_4', 'AIAgentExternal', 'SO_Actions_15', 'SOFriction', "AIToolDon't plan to use AI for this task", 'AIAgents', 'TechEndorse_6', 'AIModelsWantEntry', 'SO_Dev_Content', 'TechEndorse_8', 'TechOppose_2', 'AIAgentObsWrite', 'AIAgentChallengesStrongly agree', 'AIAgentChallengesSomewhat agree', 'AIAgentObserveSecure', 'JobSatPoints_13', 'AIHuman', 'AIAgentImpactStrongly agree', 'CommPlatformHaveEntr', 'SO_Actions_15_TEXT', 'PlatformHaveEntry', 'TechEndorse_1', 'DevEnvsChoice', 'AIAgentImpactStrongly disagree', 'CommPlatformWantToWorkWith', 'AIAgentExtWrite', 'AIAgentKnowledge', 'AIAgentChange', 'AIAgentOrchWrite', 'LearnCodeAI', 'AIToolCurrently partially AI', 'TechOppose_11', 'TechEndorse_3', 'JobSatPoints_2', 'AIAgentChallengesSomewhat disagree', 'SODuration', 'TechEndorse_13', 'WebframeChoice', 'AIAgentImpactSomewhat disagree', 'AIFrustration', 'SO_Actions_4'}

**Note:** `YearsCodePro` appears only in the 2024 survey and is not present in 2025 -> can't be used for this analysis.   
**Columns in both years:** (`LanguageHaveWorkedWith`, `ConvertedCompYearly`, `EdLevel`, `DevType`, `OrgSize`, `Country`)

In [54]:
# Confirm columns this analysis depends on exist in both years
needed_cols = ['ResponseId', 'Country', 'EdLevel', 'DevType', 'OrgSize',
               'LanguageHaveWorkedWith', 'ConvertedCompYearly']

for col in needed_cols:
    print(f"{col:25} | 2024: {col in df24.columns} | 2025: {col in df25.columns}")

ResponseId                | 2024: True | 2025: True
Country                   | 2024: True | 2025: True
EdLevel                   | 2024: True | 2025: True
DevType                   | 2024: True | 2025: True
OrgSize                   | 2024: True | 2025: True
LanguageHaveWorkedWith    | 2024: True | 2025: True
ConvertedCompYearly       | 2024: True | 2025: True

---

## 4. Filter to Scope: United States Respondents
Filtering both years to US respondents controls for currency and cost-of-living disparities across countries, so compensation comparisons by language stay meaningful.

In [55]:
df24_us = df24[df24['Country'] == 'United States of America'].copy()
df25_us = df25[df25['Country'] == 'United States of America'].copy()

df24_us.shape, df25_us.shape

((11095, 114), (7233, 172))

---